<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.0.0.379
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Karen Valerie Photography Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'karenvaleriephotography@gmail.com',
		'to' => 'karenvaleriephotography@gmail.com'
	),
	'fields' => array(
		'custom_U3259' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name: *',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name: *\' is required.'
			)
		),
		'Email' => array(
			'order' => 10,
			'type' => 'email',
			'label' => 'Email: *',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email: *\' is required.',
				'format' => 'Field \'Email: *\' has an invalid email.'
			)
		),
		'custom_U3249' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Comments: *',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U3315' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Cell Phone',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Cell Phone\' is required.'
			)
		),
		'custom_U3332' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Home Phone: *',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Home Phone: *\' is required.'
			)
		),
		'custom_U3348' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Home Address: *',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Home Address: *\' is required.'
			)
		),
		'custom_U3364' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'City: *',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'City: *\' is required.'
			)
		),
		'custom_U3380' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'State: *',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'State: *\' is required.'
			)
		),
		'custom_U3396' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Zip code: *',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Zip code: *\' is required.'
			)
		),
		'custom_U3892' => array(
			'order' => 2,
			'type' => 'radiogroup',
			'label' => 'Type of Photography: *',
			'required' => true,
			'optionItems' => array(
				'Family Portraits',
				'Senior Portraits',
				'Sport Pictures',
				'Mini session for smaller children',
				'1 hour session for older children',
				'Other (please use comment box to explain)'
			),
			'errors' => array(
				'required' => 'Field \'Type of Photography: *\' is required.',
				'format' => 'Field \'Type of Photography: *\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
